// Create, Improve, Optimize and Expand all TABLES so they contain all possible NSFW, EXPLICIT and ADULT themed content for character generation in a D&D 5e setting. This includes but is not limited to names, races, classes, backgrounds, alignments, body types, genders, orientations, kink levels, kinks, fetishes, sexual acts, power dynamics, equipment, extreme content, sexualities, dynamics, roles, toys, intensities, pairings and fluids. Ensure that the content is diverse and inclusive of all identities and preferences. The tables should be comprehensive and cover a wide range of possibilities for character creation in a D&D 5e setting.

const TABLES = {
  names: [
    "Arin",
    "Belwyn",
    "Cade",
    "Dorian",
    "Elira",
    "Fenric",
    "Galen",
    "Hestia",
    "Ilya",
    "Kael",
    "Thorne",
    "Lyra",
    "Magnus",
    "Seraphina",
    "Orion",
    "Aelion",
    "Aeris",
    "Bromdur",
    "Dagnir",
    "Bibble",
    "Coggle",
    "Brakka",
    "Drogath",
    "Alistair",
    "Beatrice",
    "Cedric",
    "Aurelia",
    "Caelus",
    "Azazel",
    "Braxia",
    "Cindros",
    "Arjhan",
    "Balasar",
    "Donaar",
    "Lysandra",
    "Morgana",
    "Velvet",
    "Scarlett",
    "Raven",
    "Jasmine",
    "Lola",
    "Candy",
    "Bambi",
    "Sienna",
    "Dahlia",
    "Violet",
    "Ruby",
    "Roxanne",
    "Chastity",
    "Faith",
    "Hope",
    "Mercy",
    "Prudence",
    "Temperance",
    "Verity",
    "Grace",
  ],
  races: [
    "Human",
    "High Elf",
    "Wood Elf",
    "Dwarf",
    "Halfling",
    "Tiefling",
    "Dragonborn",
    "Gnome",
    "Half-Orc",
    "Aasimar",
    "Goliath",
    "Fairy",
    "Nymph",
    "Succubus/Incubus",
    "Drow",
    "Half-Elf",
    "Tabaxi",
    "Kenku",
    "Demon",
    "Angel",
    "Vampire",
    "Werewolf",
    "Changeling",
    "Centaur",
    "Merfolk",
  ],
  classes: [
    "Courtesan",
    "Pleasure Slave",
    "Entertainer",
    "Bard",
    "Sorcerer",
    "Warlock",
    "Rogue",
    "Monk",
    "Cleric - Love Domain",
    "Paladin - Oath of Lust",
    "Druid",
    "Fighter",
    "Wizard",
    "Ranger",
    "Dominatrix",
    "Submissive",
    "Switch",
    "Pet",
    "Owner",
    "Master",
    "Mistress",
    "Slave",
    "Toy",
  ],
  backgrounds: [
    "Pleasure Slave",
    "Courtesan",
    "Escort",
    "Dancer",
    "Seductress/Seducer",
    "Harem Dweller",
    "Brothel Worker",
    "Street Walker",
    "Noble's Mistress",
    "Temple Prostitute",
    "Pirate's Toy",
    "Gladiator",
    "Slave",
    "Servant",
    "Noble",
    "Acolyte",
    "Criminal",
    "Entertainer",
    "Outlander",
    "BDSM Practitioner",
    "Sugar Baby",
    "Porn Star",
    "Cam Model",
    "Sex Therapist",
    "Fetish Model",
  ],
  alignments: [
    "Chaotic Good",
    "Chaotic Neutral",
    "Chaotic Evil",
    "Neutral Good",
    "True Neutral",
    "Neutral Evil",
    "Lawful Good",
    "Lawful Neutral",
    "Lawful Evil",
    "Chaotic Sexual",
    "Neutral Sexual",
  ],
  bodyTypes: [
    "Slender",
    "Athletic",
    "Curvy",
    "Voluptuous",
    "Petite",
    "Muscular",
    "Hourglass",
    "Pear",
    "Apple",
    "BBW",
    "Slim-thick",
    "Chubby",
    "Bodybuilder",
    "Twink",
    "Bear",
    "Otter",
    "Wolf",
    "Twink",
    "Bear",
    "Otter",
    "Wolf",
    "Curvy",
    "Thicc",
    "BBW",
    "Muscle",
    "Slim",
    "Stocky",
  ],
  genders: [
    "Female",
    "Male",
    "Futanari",
    "Femboy",
    "Sissy",
    "Crossdresser",
    "Ladyboy",
    "Shemale",
    "Transgender",
    "Genderfluid",
    "Non-binary",
    "Hermaphrodite",
    "Agender",
    "Bigender",
    "Demiboy",
    "Demigirl",
    "Two-Spirit",
    "Genderqueer",
    "Transmasc",
    "Transfem",
    "Genderfluid",
    "Intersex",
  ],
  orientations: [
    "Heterosexual",
    "Homosexual",
    "Bisexual",
    "Pansexual",
    "Lesbian",
    "Gay",
    "Demisexual",
    "Polyamorous",
    "Asexual",
    "Queer",
    "Omnisexual",
    "Sapiosexual",
    "Straight",
    "Bi",
    "Pan",
    "Ace",
    "Fluid",
    "Questioning",
  ],
  kinkLevels: [
    "Vanilla",
    "Curious",
    "Exploring",
    "Experienced",
    "Kinky",
    "Extreme",
    "Depraved",
  ],
  kinks: [
    "BDSM",
    "Bondage",
    "Domination",
    "Submission",
    "Sadomasochism",
    "Petplay",
    "Ageplay",
    "DDLG",
    "ABDL",
    "Furries",
    "Vore",
    "Exhibitionism",
    "Voyeurism",
    "Cuckoldry",
    "Swinging",
    "Watersports",
    "Scat",
    "Necrophilia",
    "Bestiality",
    "Incest",
    "Foot Worship",
    "Breeding",
    "Praise Kink",
    "Degradation",
    "Humiliation",
    "Edgeplay",
    "Knifeplay",
    "Bloodplay",
    "Cannibalism",
    "Guro",
    "Snuff",
    "Hypnosis",
    "Mind Control",
    "Transformation",
    "Inflation",
    "Macrophilia",
    "Microphilia",
    "BDSM",
    "Petplay",
    "DDLG",
    "Voyeurism",
    "Exhibitionism",
    "Watersports",
    "Cuckolding",
    "Pegging",
    "Shibari",
    "Edgeplay",
  ],
  fetishes: [
    "Feet",
    "Latex",
    "Leather",
    "Uniforms",
    "Pregnancy",
    "Inflation",
    "Transformation",
    "Mind Control",
    "Hypnosis",
    "Piercings",
    "Tattoos",
    "Scars",
    "Stretch Marks",
    "Body Hair",
    "Muscles",
    "Fat",
    "Skinny",
    "Tall",
    "Short",
    "Disabled",
    "Amputee",
    "Wheelchair",
  ],
  sexualActs: [
    "Oral",
    "Anal",
    "Vaginal",
    "Fisting",
    "Pegging",
    "Double Penetration",
    "Gangbang",
    "Creampie",
    "Facials",
    "Rimming",
    "Teabagging",
    "Facesitting",
    "Cunnilingus",
    "Fellatio",
    "Anilingus",
    "Breast Play",
    "Nipple Play",
    "Genital Play",
    "Ass Play",
    "Foot Play",
    "Handjob",
    "Footjob",
    "Titjob",
    "Thighjob",
    "Edging",
    "Orgasm Denial",
    "Orgasm Control",
    "Orgasm Torture",
    "Sensory Deprivation",
    "Temperature Play",
    "Wax Play",
    "Electroplay",
    "Sound Play",
    "Figging",
  ],
  powerDynamics: [
    "Master/Slave",
    "Daddy/Boy",
    "Mommy/Girl",
    "Owner/Pet",
    "Teacher/Student",
    "Boss/Employee",
    "Doctor/Patient",
    "Cop/Criminal",
    "Priest/Sinner",
    "King/Subject",
    "Queen/Subject",
    "Prince/Princess",
    "Knight/Damsel",
    "Warrior/Captive",
    "Alchemist/Test Subject",
    "Dom",
    "Sub",
    "Switch",
    "Master",
    "Slave",
    "Owner",
    "Pet",
    "Primal",
    "Handler",
    "Brat",
  ],
  equipment: [
    "Vibrators",
    "Dildos",
    "Plugs",
    "Gags",
    "Cuffs",
    "Whips",
    "Crops",
    "Chastity Devices",
    "Fucking Machines",
    "Strap-ons",
    "Harnesses",
    "Collars",
    "Leashes",
    "Blindfolds",
    "Masks",
    "Latex Suits",
    "Leather Gear",
    "Corsets",
    "Stockings",
    "Heels",
    "Boots",
    "Gloves",
    "Electrostim Devices",
    "Temperature Toys",
    "Wax Tools",
    "Knives",
    "Needles",
    "Hooks",
  ],
  extremeContent: [
    "Guro",
    "Snuff",
    "Vore",
    "Cannibalism",
    "Amputation",
    "Dismemberment",
    "Decapitation",
    "Disfigurement",
    "Mutilation",
    "Torture",
    "Crucifixion",
    "Impalement",
    "Drowning",
    "Burning",
    "Freezing",
    "Electrocution",
    "Poisoning",
    "Drugging",
    "Mindbreak",
    "Brainwashing",
    "Stockholm Syndrome",
    "Gaslighting",
    "Manipulation",
    "Coercion",
    "Blackmail",
    "Extortion",
    "Kidnapping",
    "Rape",
    "Non-con",
    "Dub-con",
    "Stockholm",
  ],
  roles: [
    "Daddy",
    "Mommy",
    "Babygirl",
    "Boy",
    "Pup",
    "Kitten",
    "Bunny",
    "Fox",
    "Little",
    "Caregiver",
  ],
  acts: [
    "Oral",
    "Anal",
    "Fisting",
    "Tease",
    "Denial",
    "Sensation",
    "Roleplay",
    "Impact",
    "Bondage",
    "Wax",
  ],
  toys: [
    "Collar",
    "Leash",
    "Cuffs",
    "Plug",
    "Whip",
    "Vibrator",
    "Dildo",
    "Gag",
    "Rope",
    "Clamps",
  ],
  intensities: ["Vanilla", "Soft", "Kinky", "Hardcore", "Extreme"],
  pairings: [
    "Monogamous",
    "Poly",
    "Open",
    "Swinging",
    "Cuckold",
    "Hotwife",
    "Gangbang",
    "Orgy",
    "Solo",
    "Group",
  ],
  fluids: [
    "Creampie",
    "Facials",
    "Bukkake",
    "Swallowing",
    "Spitting",
    "Squirting",
    "Watersports",
    "Scat",
    "Blood",
    "Lactation",
  ],
  sensoryPlay: [
    "Feathers",
    "Ice",
    "Wax",
    "Vibrations",
    "Scents",
    "Tastes",
    "Textures",
    "Sounds",
    "Lights",
    "Restriction",
  ],

  transformationStages: [
    "Initial Resistance",
    "Growing Curiosity",
    "First Submission",
    "Eager Participation",
    "Total Conversion",
    "Beyond Original Limits",
  ],

  corruptionLevels: [
    "Pure",
    "Tempted",
    "Experienced",
    "Depraved",
    "Irreversible",
    "Legendary Debauchery",
  ],
  forbiddenMagics: [
    "Orgasmomancy",
    "Flesh Sculpting",
    "Soul Binding",
    "Pleasure Paradox",
    "Eldritch Awakening",
  ],
  exoticFluids: [
    "Ichor",
    "Stardust",
    "Liquid Shadow",
    "Primordial Essence",
    "Dragon's Milk",
    "Angel's Tears",
  ],
};
