// --- Randomize ---
function rand(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function rollStat() {
  let rolls = Array.from(
    { length: 4 },
    () => Math.floor(Math.random() * 6) + 1,
  ).sort((a, b) => b - a);
  return rolls[0] + rolls[1] + rolls[2];
}

const TABLES = {
  names: [
    "Arin",
    "Arinel",
    "Arinor",
    "Arin Stoneward",
    "Arin of Greywatch",
    "Belwyn",
    "Belwyne",
    "Belwyn Ashroot",
    "Belwyn the Quiet",
    "Cade",
    "Caderin",
    "Cade Blackwater",
    "Cade of the Iron March",
    "Dorian",
    "Dorian Vale",
    "Dorian the Silver-Tongue",
    "Elira",
    "Elirath",
    "Elira Moonpetal",
    "Elira of the Dawn",
    "Fenric",
    "Fenrick",
    "Fenric Frostborn",
    "Fenric the Keen",
    "Galen",
    "Galenar",
    "Galen Stormbloom",
    "Hestia",
    "Hestiane",
    "Hestia Emberwake",
    "Ilya",
    "Ilyan",
    "Ilya of the Northwind",
    "Kael",
    "Kaelor",
    "Kael Nightstride",
    "Thorne",
    "Thornar",
    "Thorne Ironbriar",
    "Lyra",
    "Lyrath",
    "Lyra Dawnsong",
    "Magnus",
    "Magni",
    "Magnus the Red-Hand",
    "Seraphina",
    "Seraphine",
    "Seraphina Lightweaver",
    "Orion",
    "Orien",
    "Orion Starborn",

    // --- ELVEN (20) ---
    "Aelion",
    "Aeris",
    "Aestra",
    "Aethril",
    "Belthas",
    "Caelith",
    "Daerion",
    "Elowyn",
    "Faelar",
    "Galadrel",
    "Haelion",
    "Ithilwen",
    "Laeriel",
    "Maerion",
    "Naevys",
    "Olorin",
    "Raelith",
    "Saelihn",
    "Thaelar",
    "Vaerion",

    // --- DWARVEN (20) ---
    "Bromdur",
    "Dagnir",
    "Durgrim",
    "Falkrin",
    "Gimrak",
    "Harnor",
    "Kazgrim",
    "Logrim",
    "Morgran",
    "Nundar",
    "Orsik",
    "Ragni",
    "Storn",
    "Thaldrin",
    "Torvak",
    "Uldrim",
    "Vondar",
    "Wulfrin",
    "Yorgrim",
    "Zandor",

    // --- GNOMISH (20) ---
    "Bibble",
    "Coggle",
    "Dinkletop",
    "Fizzwick",
    "Gimble",
    "Hoppin",
    "Jibble",
    "Klinker",
    "Lopwick",
    "Mizzit",
    "Nackle",
    "Pipwick",
    "Quindle",
    "Rizzle",
    "Sprocket",
    "Tinklen",
    "Uzzle",
    "Vimble",
    "Whizzle",
    "Zibbit",

    // --- ORCISH (20) ---
    "Brakka",
    "Drogath",
    "Gorvak",
    "Hroth",
    "Kragga",
    "Loktar",
    "Morgash",
    "Nargul",
    "Orvok",
    "Ragthar",
    "Sharn",
    "Throg",
    "Urgash",
    "Varok",
    "Wargul",
    "Xarg",
    "Yorvak",
    "Zugrash",
    "Grakka",
    "Bolthar",

    // --- HUMAN MEDIEVAL (20) ---
    "Alistair",
    "Beatrice",
    "Cedric",
    "Dunstan",
    "Evelyn",
    "Fendrel",
    "Garrick",
    "Helena",
    "Isolde",
    "Jareth",
    "Kendrick",
    "Lorian",
    "Maribel",
    "Nolan",
    "Oswin",
    "Percival",
    "Rowena",
    "Selwyn",
    "Tristan",
    "Wynne",

    // --- CELESTIAL / AASIMAR (20) ---
    "Aurelia",
    "Caelus",
    "Divinia",
    "Elyndor",
    "Fayriel",
    "Gavriel",
    "Halion",
    "Illiara",
    "Jophiel",
    "Kaelis",
    "Lumina",
    "Mirael",
    "Neriah",
    "Ophira",
    "Phaelon",
    "Quorin",
    "Raviel",
    "Serion",
    "Tiriel",
    "Urielle",

    // --- INFERNAL / TIEFLING (20) ---
    "Azazel",
    "Braxia",
    "Cindros",
    "Draeva",
    "Erebus",
    "Fyria",
    "Graxus",
    "Havria",
    "Ixion",
    "Jezra",
    "Khalix",
    "Lazira",
    "Mordai",
    "Nerox",
    "Orzhira",
    "Pyrion",
    "Ravox",
    "Sazira",
    "Tyrnox",
    "Vezra",

    // --- DRACONIC / DRAGONBORN (20) ---
    "Arjhan",
    "Balasar",
    "Donaar",
    "Ghesh",
    "Heskan",
    "Kriv",
    "Medrash",
    "Nadarr",
    "Pandjed",
    "Raiann",
    "Rhogar",
    "Shamash",
    "Shedinn",
    "Tarhun",
    "Torinn",
    "Uadjit",
    "Vyth",
    "Wystan",
    "Zedaar",
    "Zorvath",
  ],
  races: [
    // --- HUMAN (11) ---
    "Human",
    "Highlander Human",
    "Desert Nomad Human",
    "Imperial Human",
    "Seafarer Human",
    "Witch‑blooded Human",
    "Frontier Settler Human",
    "Scholar‑Caste Human",
    "Raider‑Clan Human",
    "Urbanite Human",
    "Mystic‑Touched Human",

    // --- ELF (11) ---
    "Elf",
    "High Elf",
    "Wood Elf",
    "Moon Elf",
    "Sun Elf",
    "Shadow Elf",
    "Sea Elf",
    "Star Elf",
    "Ashen Elf",
    "Frost Elf",
    "Thorn Elf",

    // --- DWARF (11) ---
    "Dwarf",
    "Mountain Dwarf",
    "Hill Dwarf",
    "Deep Dwarf",
    "Ember‑Forge Dwarf",
    "Stone‑Seer Dwarf",
    "Ironbreaker Dwarf",
    "Runecarver Dwarf",
    "Frostbeard Dwarf",
    "Goldvein Dwarf",
    "Blackhammer Dwarf",

    // --- HALFLING (7) ---
    "Halfling",
    "Lightfoot Halfling",
    "Stout Halfling",
    "Riverfolk Halfling",
    "Burrow‑kin Halfling",
    "Wanderer Halfling",
    "Hearth‑born Halfling",

    // --- TIEFLING (11) ---
    "Tiefling",
    "Infernal Tiefling",
    "Abyssal Tiefling",
    "Ash‑skin Tiefling",
    "Ember‑blood Tiefling",
    "Shadow‑horn Tiefling",
    "Bone‑crowned Tiefling",
    "Iron‑tailed Tiefling",
    "Frost‑touched Tiefling",
    "Void‑marked Tiefling",
    "Gloom‑born Tiefling",

    // --- DRAGONBORN (11) ---
    "Dragonborn",
    "Red Dragonborn",
    "Blue Dragonborn",
    "Green Dragonborn",
    "Black Dragonborn",
    "White Dragonborn",
    "Brass Dragonborn",
    "Bronze Dragonborn",
    "Copper Dragonborn",
    "Gold Dragonborn",
    "Silver Dragonborn",

    // --- GNOME (9) ---
    "Gnome",
    "Rock Gnome",
    "Forest Gnome",
    "Tinker Gnome",
    "Illusionist Gnome",
    "Deep Gnome",
    "Clockwork Gnome",
    "Ember‑spark Gnome",
    "Mist‑whisper Gnome",

    // --- HALF‑ORC (7) ---
    "Half‑Orc",
    "Clan‑born Half‑Orc",
    "City‑blood Half‑Orc",
    "War‑scarred Half‑Orc",
    "Spirit‑touched Half‑Orc",
    "Iron‑jaw Half‑Orc",
    "Frost‑fang Half‑Orc",

    // --- AASIMAR (9) ---
    "Aasimar",
    "Protector Aasimar",
    "Scourge Aasimar",
    "Fallen Aasimar",
    "Dawn‑blessed Aasimar",
    "Star‑touched Aasimar",
    "Radiant‑soul Aasimar",
    "Oracle‑blood Aasimar",
    "Empyrean‑kin Aasimar",

    // --- GOLIATH (7) ---
    "Goliath",
    "Stonehide Goliath",
    "Skywatcher Goliath",
    "Frostpeak Goliath",
    "Boulder‑born Goliath",
    "Thunder‑stride Goliath",
    "Iron‑ridge Goliath",
  ],
  classes: [
    // --- FIGHTER (11) ---
    "Fighter",
    "Fighter — Champion",
    "Fighter — Battle Master",
    "Fighter — Eldritch Knight",
    "Fighter — Gladiator",
    "Fighter — Warlord",
    "Fighter — Duelist",
    "Fighter — Vanguard",
    "Fighter — Mercenary",
    "Fighter — Knight‑Errant",
    "Fighter — Monster‑Hunter",

    // --- WIZARD (11) ---
    "Wizard",
    "Wizard — Evoker",
    "Wizard — Illusionist",
    "Wizard — Necromancer",
    "Wizard — Diviner",
    "Wizard — Abjurer",
    "Wizard — Transmuter",
    "Wizard — Chronomancer",
    "Wizard — Runewright",
    "Wizard — Storm‑Mage",
    "Wizard — Void Scholar",

    // --- ROGUE (11) ---
    "Rogue",
    "Rogue — Thief",
    "Rogue — Assassin",
    "Rogue — Arcane Trickster",
    "Rogue — Scout",
    "Rogue — Swashbuckler",
    "Rogue — Shadowblade",
    "Rogue — Poisoner",
    "Rogue — Infiltrator",
    "Rogue — Gambler",
    "Rogue — Street Ghost",

    // --- CLERIC (11) ---
    "Cleric",
    "Cleric — Life Domain",
    "Cleric — Light Domain",
    "Cleric — War Domain",
    "Cleric — Tempest Domain",
    "Cleric — Grave Domain",
    "Cleric — Trickery Domain",
    "Cleric — Knowledge Domain",
    "Cleric — Forge Domain",
    "Cleric — Nature Domain",
    "Cleric — Order Domain",

    // --- BARBARIAN (11) ---
    "Barbarian",
    "Barbarian — Berserker",
    "Barbarian — Totem Warrior",
    "Barbarian — Storm Herald",
    "Barbarian — Zealot",
    "Barbarian — Beast‑Heart",
    "Barbarian — Juggernaut",
    "Barbarian — Ravager",
    "Barbarian — Frost‑blood",
    "Barbarian — Flame‑born",
    "Barbarian — Spirit‑Caller",

    // --- RANGER (11) ---
    "Ranger",
    "Ranger — Hunter",
    "Ranger — Beastmaster",
    "Ranger — Horizon Walker",
    "Ranger — Gloom Stalker",
    "Ranger — Monster Slayer",
    "Ranger — Trapper",
    "Ranger — Warden",
    "Ranger — Scout",
    "Ranger — Wildrunner",
    "Ranger — Storm‑Tracker",

    // --- PALADIN (11) ---
    "Paladin",
    "Paladin — Devotion",
    "Paladin — Vengeance",
    "Paladin — Ancients",
    "Paladin — Conquest",
    "Paladin — Redemption",
    "Paladin — Oathbreaker",
    "Paladin — Dawn‑Knight",
    "Paladin — Ironbound",
    "Paladin — Star‑Ward",
    "Paladin — Flame‑Vow",

    // --- BARD (11) ---
    "Bard",
    "Bard — College of Lore",
    "Bard — College of Valor",
    "Bard — College of Glamour",
    "Bard — College of Swords",
    "Bard — College of Whispers",
    "Bard — Satirist",
    "Bard — Skald",
    "Bard — Dream‑Singer",
    "Bard — Shadow‑Minstrel",
    "Bard — Battle‑Chanter",

    // --- WARLOCK (11) ---
    "Warlock",
    "Warlock — Fiend Patron",
    "Warlock — Archfey Patron",
    "Warlock — Great Old One Patron",
    "Warlock — Hexblade Patron",
    "Warlock — Celestial Patron",
    "Warlock — Undying Patron",
    "Warlock — Void‑Pact",
    "Warlock — Storm‑Pact",
    "Warlock — Bone‑Pact",
    "Warlock — Mirror‑Pact",

    // --- DRUID (11) ---
    "Druid",
    "Druid — Circle of the Land",
    "Druid — Circle of the Moon",
    "Druid — Circle of Dreams",
    "Druid — Circle of the Shepherd",
    "Druid — Circle of Spores",
    "Druid — Circle of Stars",
    "Druid — Circle of Wildfire",
    "Druid — Circle of Stone‑root",
    "Druid — Circle of the Tide",
    "Druid — Circle of the Sky",

    // --- MONK (11) ---
    "Monk",
    "Monk — Way of the Open Hand",
    "Monk — Way of Shadow",
    "Monk — Way of Four Elements",
    "Monk — Way of the Sun Soul",
    "Monk — Way of the Long Death",
    "Monk — Way of the Kensei",
    "Monk — Way of the Astral Self",
    "Monk — Way of the Drunken Master",
    "Monk — Way of the Iron Body",
    "Monk — Way of the Wind‑Step",

    // --- SORCERER (11) ---
    "Sorcerer",
    "Sorcerer — Draconic Bloodline",
    "Sorcerer — Wild Magic",
    "Sorcerer — Shadow Magic",
    "Sorcerer — Storm Sorcery",
    "Sorcerer — Divine Soul",
    "Sorcerer — Aberrant Mind",
    "Sorcerer — Pyromancer",
    "Sorcerer — Frost‑born",
    "Sorcerer — Bloodline Sorcery",
    "Sorcerer — Star‑Touched",
  ],
  backgrounds: [
    // --- SOLDIER (9) ---
    "Soldier",
    "Soldier — Infantry Veteran",
    "Soldier — Cavalry Scout",
    "Soldier — Siege Engineer",
    "Soldier — Banner‑Bearer",
    "Soldier — Veteran Sergeant",
    "Soldier — Mercenary Footman",
    "Soldier — War Drummer",
    "Soldier — Battlefield Medic",

    // --- SAGE (9) ---
    "Sage",
    "Sage — Archivist",
    "Sage — Arcanist",
    "Sage — Historian",
    "Sage — Linguist",
    "Sage — Astronomer",
    "Sage — Chronicler",
    "Sage — Researcher",
    "Sage — Forbidden Scholar",

    // --- CRIMINAL (9) ---
    "Criminal",
    "Criminal — Thief",
    "Criminal — Smuggler",
    "Criminal — Enforcer",
    "Criminal — Fence",
    "Criminal — Pickpocket",
    "Criminal — Burglar",
    "Criminal — Con‑Artist",
    "Criminal — Blackmailer",

    // --- NOBLE (9) ---
    "Noble",
    "Noble — Courtier",
    "Noble — Aristocrat",
    "Noble — Exiled Noble",
    "Noble — Diplomat",
    "Noble — Heir Apparent",
    "Noble — Fallen House Scion",
    "Noble — Knight‑Retainer",
    "Noble — Patron of the Arts",

    // --- HERMIT (9) ---
    "Hermit",
    "Hermit — Wilderness Hermit",
    "Hermit — Visionary",
    "Hermit — Mad Prophet",
    "Hermit — Alchemist Recluse",
    "Hermit — Cave‑Dweller",
    "Hermit — Exile",
    "Hermit — Mystic",
    "Hermit — Herbalist",

    // --- ACOLYTE (9) ---
    "Acolyte",
    "Acolyte — Temple Servant",
    "Acolyte — Choir Initiate",
    "Acolyte — Shrine Keeper",
    "Acolyte — Pilgrim",
    "Acolyte — Exorcist",
    "Acolyte — Scribe",
    "Acolyte — Relic‑Bearer",
    "Acolyte — Penitent",

    // --- OUTLANDER (9) ---
    "Outlander",
    "Outlander — Hunter",
    "Outlander — Nomad",
    "Outlander — Beast‑Rider",
    "Outlander — Forager",
    "Outlander — Trailblazer",
    "Outlander — Mountain‑born",
    "Outlander — Swamp‑walker",
    "Outlander — Desert‑runner",

    // --- CHARLATAN (9) ---
    "Charlatan",
    "Charlatan — Fortune Teller",
    "Charlatan — Fake Healer",
    "Charlatan — Card Shark",
    "Charlatan — Identity Forger",
    "Charlatan — Snake‑Oil Seller",
    "Charlatan — Trickster",
    "Charlatan — Impersonator",
    "Charlatan — Street Prophet",

    // --- FOLK HERO (9) ---
    "Folk Hero",
    "Folk Hero — Village Defender",
    "Folk Hero — Rebel",
    "Folk Hero — Farmhand",
    "Folk Hero — Local Legend",
    "Folk Hero — Monster‑Slayer",
    "Folk Hero — Shepherd",
    "Folk Hero — Carpenter’s Apprentice",
    "Folk Hero — Runaway",

    // --- GUILD ARTISAN (9) ---
    "Guild Artisan",
    "Guild Artisan — Smith",
    "Guild Artisan — Weaver",
    "Guild Artisan — Carpenter",
    "Guild Artisan — Alchemist",
    "Guild Artisan — Jeweler",
    "Guild Artisan — Cartographer",
    "Guild Artisan — Scribe",
    "Guild Artisan — Shipwright",
  ],
  alignments: [
    // --- LAWFUL GOOD (11) ---
    "Lawful Good",
    "Lawful Good — The Justicar",
    "Lawful Good — The Shield",
    "Lawful Good — The Martyr",
    "Lawful Good — The Watchman",
    "Lawful Good — The Oath‑Keeper",
    "Lawful Good — The Guardian",
    "Lawful Good — The Arbiter",
    "Lawful Good — The Saint",
    "Lawful Good — The Banner‑Bearer",
    "Lawful Good — The Protector",

    // --- NEUTRAL GOOD (11) ---
    "Neutral Good",
    "Neutral Good — The Healer",
    "Neutral Good — The Mediator",
    "Neutral Good — The Shepherd",
    "Neutral Good — The Quiet Hero",
    "Neutral Good — The Peacemaker",
    "Neutral Good — The Samaritan",
    "Neutral Good — The Mentor",
    "Neutral Good — The Advocate",
    "Neutral Good — The Altruist",
    "Neutral Good — The Lantern",

    // --- CHAOTIC GOOD (11) ---
    "Chaotic Good",
    "Chaotic Good — The Rebel",
    "Chaotic Good — The Liberator",
    "Chaotic Good — The Trickster‑Hero",
    "Chaotic Good — The Firebrand",
    "Chaotic Good — The Outlaw‑Saint",
    "Chaotic Good — The Wild‑Heart",
    "Chaotic Good — The Iconoclast",
    "Chaotic Good — The Freedom‑Fighter",
    "Chaotic Good — The Storm‑Child",
    "Chaotic Good — The Rogue‑Angel",

    // --- LAWFUL NEUTRAL (11) ---
    "Lawful Neutral",
    "Lawful Neutral — The Judge",
    "Lawful Neutral — The Magistrate",
    "Lawful Neutral — The Arbiter",
    "Lawful Neutral — The Bureaucrat",
    "Lawful Neutral — The Lawscribe",
    "Lawful Neutral — The Enforcer",
    "Lawful Neutral — The Warden",
    "Lawful Neutral — The Keeper",
    "Lawful Neutral — The Adjudicator",
    "Lawful Neutral — The Regulator",

    // --- TRUE NEUTRAL (11) ---
    "True Neutral",
    "True Neutral — The Observer",
    "True Neutral — The Druid",
    "True Neutral — The Hermit",
    "True Neutral — The Wanderer",
    "True Neutral — The Mediator",
    "True Neutral — The Stoic",
    "True Neutral — The Watcher",
    "True Neutral — The Balanced",
    "True Neutral — The Unmoved",
    "True Neutral — The Gray Sage",

    // --- CHAOTIC NEUTRAL (11) ---
    "Chaotic Neutral",
    "Chaotic Neutral — The Trickster",
    "Chaotic Neutral — The Wanderer",
    "Chaotic Neutral — The Wildcard",
    "Chaotic Neutral — The Unbound",
    "Chaotic Neutral — The Storm‑Walker",
    "Chaotic Neutral — The Madcap",
    "Chaotic Neutral — The Free Spirit",
    "Chaotic Neutral — The Rogue",
    "Chaotic Neutral — The Instigator",
    "Chaotic Neutral — The Whim‑Chaser",

    // --- LAWFUL EVIL (11) ---
    "Lawful Evil",
    "Lawful Evil — The Tyrant",
    "Lawful Evil — The Iron Fist",
    "Lawful Evil — The Schemer",
    "Lawful Evil — The Magistrate of Pain",
    "Lawful Evil — The Enslaver",
    "Lawful Evil — The Dark Judge",
    "Lawful Evil — The Contract‑Binder",
    "Lawful Evil — The Enforcer",
    "Lawful Evil — The Strategist",
    "Lawful Evil — The Black Inquisitor",

    // --- NEUTRAL EVIL (11) ---
    "Neutral Evil",
    "Neutral Evil — The Manipulator",
    "Neutral Evil — The Poisoner",
    "Neutral Evil — The Betrayer",
    "Neutral Evil — The Usurper",
    "Neutral Evil — The Whisperer",
    "Neutral Evil — The Corrupter",
    "Neutral Evil — The Grave‑Dealer",
    "Neutral Evil — The Shadow Broker",
    "Neutral Evil — The Profiteer",
    "Neutral Evil — The Viper",

    // --- CHAOTIC EVIL (11) ---
    "Chaotic Evil",
    "Chaotic Evil — The Destroyer",
    "Chaotic Evil — The Ravager",
    "Chaotic Evil — The Mad Prophet",
    "Chaotic Evil — The Bloodletter",
    "Chaotic Evil — The Anarch",
    "Chaotic Evil — The Demon‑Spawn",
    "Chaotic Evil — The Reaver",
    "Chaotic Evil — The Chaos‑Bringer",
    "Chaotic Evil — The Howling One",
    "Chaotic Evil — The World‑Eater",
  ],
};

function randomizeSheet() {
  setValue("charName", rand(TABLES.names));
  setValue("race", rand(TABLES.races));
  let cls = rand(TABLES.classes);
  setValue("classLevel", `${cls} 1`);
  setValue("background", rand(TABLES.backgrounds));
  setValue("alignment", rand(TABLES.alignments));
  setValue("level", 1);

  ["str", "dex", "con", "int", "wis", "cha"].forEach((ab) =>
    setValue(`${ab}Score`, rollStat()),
  );

  document.querySelectorAll(".save-prof, .skill-prof").forEach((cb) => {
    cb.checked = Math.random() < 0.3;
  });
  document.querySelectorAll('[id^="exp_"], [id^="saveExp_"]').forEach((cb) => {
    cb.checked = Math.random() < 0.1;
  });

  recalc();
}
